### ISSUE TITLE
[TODO] 2017/08/05

### ISSUE THREAD

**Issue by bruce30262** [bruce30262/TWindbg#3]
- [x] enhance smart dereference
    - [x] detect type (  code / string / raw data )
    - [x] support `telescope` command
- [x] `context` : print out the current context 
- [x] help command ( list the TWindbg command )
